### ISSUE TITLE
Error running app 

### ISSUE THREAD

**Issue by rajkamaludaya** [OpenCV-AI-Courses/RadiologyAI-App#2]
When I try to upload the model for evaluation , I do see below error.

Oh no.
Error running app. If this keeps happening, please contact support 

![image](https://user-images.githubusercontent.com/101932829/159769434-2ba73dea-3d9d-4313-80dd-23275672ec07.png)

**Comment by OpenCV-AI-Courses** [comment]
App has been updated. Thank you for bringing this to our notice.

**Comment by OpenCV-AI-Courses** [comment]
Hi ​  ​   Apologies for the delay. We were working on it.    This issue usually occurs when the model size is greater than 700MB. Larger models causes resource bottleneck on the streamlit app. Could you verify whether that is not the case, i.e., your model’s size is less than 700MB?   The team is notified about the crash, and the app will be rebooted in some time.        ---------------   Best Regards  Team OpenCV Courses     Happy Learning :)  
                           
                            On
                            Wed, 23 Mar at 11:23 AM
                            ,  OpenCV-AI-Courses/RadiologyAI-App ***@***.***>  wrote:
                             
 When I try to upload the model for evaluation , I do see below error. 
 Oh no. 
Error running app. If this keeps happening, please contact support
